name: 编译主程序

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - name: Load VERSION
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.0
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -o doh-client-${{matrix.goos}}-${{matrix.goarch}} ./main.go
      - name: Package
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: sudo tar -czvf doh-client-${{matrix.goos}}-${{matrix.goarch}}.tar.gz ./doh-client-${{matrix.goos}}-${{matrix.goarch}} # 将可执行文件打包为 tar.gz
      - name: 上传至Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.VERSION }}
          artifacts: ./doh-client*.tar.gz, ./doh-client*
          token: ${{ secrets.REPO_TOKEN }}
          tag: ${{ env.VERSION }}
          allowUpdates: true
        env:
          export PATH: $PATH:/usr/local/go/bin
